### ISSUE TITLE
Feature: Releases w/ npm packaging

### ISSUE THREAD

**Issue by saulimus** [ExaVault/evapi-javascript#1]
Some feature requests:

- Releases
- This project available as an npm package

Reason:
Using this library in a project requires a script that does git clone, git reset to a specific sha1 (to ensure a certain version) + npm link. I think this is too cumbersome and haven't found this kind of approach in other projects. Is there a reason not to use npm?

**Comment by wolasss** [comment]
+1 Why this is not available as an npm package?

**Comment by AmyExaVault** [comment]
That's a fine question. We use swagger to generate these client libraries, so what we've got here is what comes out of there. I'll research how to get that packaged up into npm. It's not going to happen this month, but I'll add an update when that's scheduled.

**Comment by AmyExaVault** [comment]
Good news. Just 1 1/2 short years later, https://www.npmjs.com/package/@exavault/exavault-api
